sudo: required
services:
    - docker
before_install:
    - docker build -t uzumakinaruto/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true uzumakinaruto/react-test npm test

after_success:
    - docker build -t uzumakinaruto/multi-client ./client
    - docker build -t uzumakinaruto/multi-nginx ./nginx
    - docker build -t uzumakinaruto/multi-server ./server
    - docker build -t uzumakinaruto/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push to dockerHub
    - docker push uzumakinaruto/multi-client
    - docker push uzumakinaruto/multi-nginx
    - docker push uzumakinaruto/multi-server
    - docker push uzumakinaruto/multi-worker